lists2safebrowsing.py
This currently prevents the entity whitelist from being generated.
=> Deal with UTF-8 entity names

lists2safebrowsing.py
These lists will be available in production but will be used to stage new entries in the client.
The matching config change is https://github.com/mozilla-services/shavar-list-creation-config/pull/9.
=> Add staging lists

lists2safebrowsing.py, sample_shavar_list_creation.ini
Bug 1425075 - config categories for each list
sample ads, analytics, and social list configs
refactor a default_disconnect_url config
To deploy:
1. [ ] Merge this PR to add this new logic
2. [ ] Merge [`shavar-list-creation-config` PR](https://github.com/mozilla-services/shavar-list-creation-config/pull/25) adding the ads, analytics, and social
3. [ ] Test the resulting lists on the stage server
4. [ ] Send the same PR adding ads, analytics, and social configs to https://github.com/mozilla-services/shavar-list-creation-config/blob/master/prod.ini
5. [ ] Test the resulting lists on the prod server
=> (WIP, Do Not Merge) Bug 1425075 - config categories for each list

.gitignore
This lets me use this repository as a git submodule without git complaining about untracked changes. As an example, see: https://github.com/mozilla/trackingprotection-tools.
=> Ignore compiled python files in `.gitignore`

lists2safebrowsing.py, sample_shavar_list_creation.ini
This PR adds support for parsing our the `fingerprinting` and `cryptomining` portions of the Disconnect list. I checked the logs for the generated lists and spot checked them against the domains generated by [a separate parser](https://github.com/mozilla/trackingprotection-tools/blob/master/DisconnectParser.py).
=> Add support for tagged domains in list creation script

lists2safebrowsing.py, sample_shavar_list_creation.ini
This does two things:
* Updates for changes in the list format in https://github.com/mozilla-services/shavar-prod-lists/pull/54
* Fixes #57. I wasted some time trying to figure out why the the content list doesn't look right while testing some new changes with the sample config.
=> Update sample config

lists2safebrowsing.py
This is the result of a run of autopep8 plus some manual editing. While the diff is impossible to read, we can confirm that it produces the same output:
First, we can compare the list contents using `cat *digest256.log | sort | md5sum`. I use the log files as a proxy since the actual lists aren't sorted and can't be easily sorted.
Current master with current prod.ini: `8802d79f6e4298d445d06f34484ad540`
This PR with current prod.ini: `8802d79f6e4298d445d06f34484ad540`
Second, we can compare the number of items in each list.
Current master run on current prod.ini:
```
Tracking protection(tracking-protection-base): publishing 1897 items; file size 60726
Tracking protection(tracking-protection-baseeff): publishing 2 items; file size 83
Tracking protection(tracking-protection-basew3c): …
```
=> Fix PEP8 errors and warnings in list creation script

.gitignore, disconnect_mapping.json, lists2safebrowsing.py, requirements.txt
I've replicated the parsing logic in an [external library](https://github.com/mozilla/trackingprotection-tools/blob/4a1c0e1aea588e952264f5d0a98acdc075d36050/trackingprotection_tools/DisconnectParser.py). This PR switches `lists2safebrowsing` over to the external library.
This has a few clear benefits:
* I need to run analyses using the Disconnect list, so I've had to replicate the `lists2safebrowsing` logic. Prior to this I've had to effectively maintain two slightly different implementations with each structural change.
* The new parser has [fairly comprehensive test suite](https://github.com/mozilla/trackingprotection-tools/blob/4a1c0e1aea588e952264f5d0a98acdc075d36050/trackingprotection_tools/test/test_disconnect_parser.py), which will hopefully take a lot of the guess work and manual …
=> Refactor the list parsing script to use a dedicated parser library

lists2safebrowsing.py, sample_shavar_list_creation.ini
I recommend merging #71 and #72 first. After that, I'll rebase this and the diff should be much easier to read.
In https://github.com/mozilla-services/shavar-prod-lists/pull/56 Disconnect created a new top-level `Fingerprinting` category, which contains all fingerprinting domains irrespective of their tracking classification. This PR updates the list creation script to support compound and exclusion category filters, such as those specified in the new config (https://github.com/mozilla-services/shavar-list-creation-config/pull/45).
I migrated the `disconnect_categories` option over to a `categories` option with slightly different syntax. In the new format, `OR` category filters should use the `|` delimiter and `AND` category filters should use `,`. All of the old filters were `OR` (i.e., …
=> Support new fingerprinting list format.

publish2cloud.py
=> Add remote settings config check

publish2cloud.py
After running the https://github.com/mozilla-services/shavar-list-creation/pull/86 changes we noted that the S3 were acting differently. To make sure that old functionalities are not changed, this PR applies the following:
=> Default upload_to_s3 as True

constants.py, lists2safebrowsing.py, publish2cloud.py, requirements.txt, sample_shavar_list_creation.ini
As mentioned in https://github.com/mozilla-services/shavar-list-creation/issues/90, adding versioning to S3 was pushed higher in the priority because we want versioning before merging new lists published from [Disconnect](https://github.com/mozilla-services/shavar-prod-lists/pull/76) to ascertain that the new lists are not unexpectedly breaking websites thus disrupting millions of users who use Firefox to surfing the web. This PR uses the versioned branch(s) available on [Shavar prod lists repo](https://github.com/mozilla-services/shavar-prod-lists) to publish versioned lists to S3
#
Depends on config changes https://github.com/mozilla-services/shavar-list-creation-config/pull/56
=> Version tracking lists and publish to S3

publish2cloud.py
#93 is caused by Remote Settings endpoint not being available to Jenkins since Remote Settings is behind a VPN. This PR handles connection issue to Remote Settings and gracefully exits so that S3 can continue to run as it did.
=> Graceful exit when Remote Settings returns a ConnectionError

publish2cloud.py
As mentioned in #97, this PR times out the connection if no response is sent in 10 secs using `timeout` in Python's build-in package `requests` as mentioned [here](https://requests.kennethreitz.org//en/master/user/advanced/#timeouts)
=> Timeout connection to Remote Settings after 10s

lists2safebrowsing.py
While implementing features on Shavar service as mentioned in https://github.com/mozilla-services/shavar-list-creation/issues/90, in order to ascertain that the versioned list is being used by the client we need a test domain that only exists in the said versioned list. This PR adds a static versioned test domain in the versioned lists with the following naming convention: `<version>.<list name>.dummytracker.org` like `71.0.base-fingerprinting-track-digest256.dummytracker.org`
1. Go to this [line](https://github.com/mozilla-services/shavar-list-creation/pull/103/commits/8c3d243a0acd54dca95a1074927e48ec21414b11#diff-8c5c15d9cbbefc2ec320aa3f2a253290R274)
2. Add an easily identifable print statement with the domain to be printed on the terminal
3. Run `python ./lists2safebrowsing.py` and …
=> Add versioned static test domain

lists2safebrowsing.py, publish2cloud.py
To get the proper versioned list from S3 as requested on https://github.com/mozilla-services/shavar-list-creation/issues/90 its respective chunknum (timestamp of when the list was created) should also be available AND be differentiated from the lists created from the master branch. This PR solves that issue by creating a folder inside the chunknum folder of each list and storing the chunk num in that folder.
=> Publish versioned chunk num on s3

lists2safebrowsing.py
After the changes introduced in https://github.com/mozilla-services/shavar-list-creation/pull/103, QAs are unable to test that ETP works on https://senglehardt.com/test/trackingprotection/test_pages/ since the static test domains on versioned lists were replaced by versioned test domains (e.g. https://70-0-social-tracking-protection-facebook-digest256.dummytracker.org/ instead or https://social-tracking-protection-facebook-digest256.dummytracker.org/). Versioned lists should have static test domains and the test domains with version as the prefix so QAs can test that ETP works on all channels.
=> Add static test domains to versioned lists

publish2cloud.py
If this isn't applied when the file is created, or after, it will silently fail.
=> properly apply the canned acl

.circleci/config.yml
Add a CircleCI step that copies `sample_shavar_list_creation.ini` to `shavar_list_creation.ini`, in order to prevent the tests from failing.
=> Create config file before running tests

lists2safebrowsing.py, requirements.txt, sample_shavar_list_creation.ini, tests/test_lists2safebrowsing.py
Test that `add_domain_to_list` adds a domain to a blocklist and produces the expected log output. Also, test that `add_domain_to_list` does not add public suffix domains to the list. Finally, test that it does not add domains to the list twice. Closes #136
Note: currently `test_add_domain_to_list_duplicate` is failing for the reason described in https://github.com/mozilla-services/shavar-list-creation/issues/136#issuecomment-642851266
=> Add unit tests for add_domain_to_list

.circleci/config.yml, .gitignore, README.md, requirements.txt
This PR:
- Configures coverage reporting
- Corrects the order of instructions in the README, to prevent the tests from failing because there is no configuration file.
=> Configure coverage reporting

lists2safebrowsing.py, tests/test_lists2safebrowsing.py
Implement unit tests to validate Safe Browsing v2 blocklist generation. Include a test where the versioned test domain is not included in the blocklist and another test where both test domains are omitted, in order to ensure full branch coverage. Closes #137
Note: Right now these unit tests are failing because of the `previous_domains` bug mentioned in https://github.com/mozilla-services/shavar-list-creation/issues/136#issuecomment-642851266. They will be passing once https://github.com/mozilla-services/shavar-list-creation/pull/141 is merged.
Also closes #49.
=> Add unit tests for blocklist and entity list generation

lists2safebrowsing.py, tests/sample_blocklist.json, tests/test_lists2safebrowsing.py
This PR adds:
-  a unit test that validates the implementation of `get_domains_from_category_filters`
- a unit test that confirms that `get_domains_from_category_filters` raises a `ValueError` when receiving invalid input
- a sample blocklist JSON file to be used in the tests
**Update**: the following have been added to this PR:
- unit tests for `get_domains_from_filters`
- unit tests for `get_tracker_lists`
=> Add unit tests for domain filtering and get_tracker_lists

publish2cloud.py
Handle error on stage from Remote Settings
```
------ tracking-protection-content-cryptomining ------
-->blocklist: https://raw.githubusercontent.com/mozilla-services/shavar-prod-lists/master/disconnect-blacklist.json)
* filter ['Content'] matched 483 domains
* filter ['Cryptomining'] matched 69 domains. Reduced set to 0 items.
* removing 1 rule(s) due to DNT exceptions
Tracking protection(tracking-protection-content-cryptomining): publishing 1 items; file size 51
Traceback (most recent call last):
File "lists2safebrowsing.py", line 684, in <module>
main()
File "lists2safebrowsing.py", line 672, in main
publish_to_cloud(config, chunknum)
File "/home/jenkins/slave/workspace/pipelines/ShavarListCreation/shavar-list-creation/publish2cloud.py", line 301, in publish_to_cloud
config, section, …
```
=> Handle requests.exceptions.ReadTimeout

lists2safebrowsing.py, sample_shavar_list_creation.ini, tests/sample_blocklist.json, tests/test_lists2safebrowsing.py
According to changes on https://github.com/mozilla-services/shavar-prod-lists/pull/284 we are now using "FingerprintInvasive" instead of "Fingerprint" category
Related to https://github.com/mozilla-services/shavar-prod-lists/pull/284
=> Update sample configuration with new fingerprinting category name

publish2cloud.py, requirements.txt, tests/test_publish2cloud.py
Implement unit tests for `chunk_metadata`, `new_data_to_publish_to_s3` and `publish_to_s3`.
Will close #130.
=> Add unit tests for publish2cloud.py

lists2safebrowsing.py, tests/test_lists2safebrowsing.py
This PR makes sure we sort the domains before writing their hashes to the safebrowsing list files. This way, we ensure that any changes in the order of domains in the input lists will not trigger unnecessary list updates.
Additionally, this is a prerequisite for porting the list creation script to Python 3. [Hash randomization is enabled by default starting from Python 3.3](https://docs.python.org/3/whatsnew/3.3.html#builtin-functions-and-types) and this would result in a differently ordered list being created every time the script is run.
Addresses #132.
Notes:
* The dummytracker domains are exempt from ordering and remain at the top of the lists
* In the case of entity lists, URLs are primarily sorted based on the entity name and there is a secondary alphanumeric ordering within each …
=> Order domains alphanumerically in safebrowsing lists

.circleci/config.yml, README.md, lists2safebrowsing.py, publish2cloud.py, requirements.txt, tests/test_lists2safebrowsing.py, tests/test_publish2cloud.py
This PR makes the necessary changes to enable the script to run under Python 3 and drops Python 2 support.
**Note**: Since Python 3.3 [hash randomization is enabled by default](https://docs.python.org/3/whatsnew/3.3.html#builtin-functions-and-types). This means that the order of domains in the lists will be different every time the script is run, causing unnecessary list updates. Enforcing alphanumeric ordering in domains when writing the lists will resolve this. Consequently, this PR should not be merged before #132 is closed.
This is also why `test_get_plugin_lists()` and `test_get_tracker_lists()` are failing most of the time.
What is more, running the script currently fails with `UnicodeDecodeError` when `chunk_metadata()` tries to decode bytes after the end of the chunk header. This …
=> Port script to Python 3

.circleci/config.yml, requirements-test.txt, requirements.txt
Separating the test requirements prevents the Jenkins job from installing packages that won't be used.
=> Separate test requirements

lists2safebrowsing.py
GitHub API returns 30 results per page as defined [here](https://docs.github.com/en/rest/branches/branches). As a result, the script was only generating versioned shavar lists up until 99.0 (instead of 102.0). To fix this bug, we should grab all branches so the script creates versioned lists for all branches and not the first 30 is the GitHub API defaults to.
=> Make GitHub API return all branches

constants.py, lists2safebrowsing.py
Email tracker category was introduced in https://github.com/mozilla-services/shavar-prod-lists/pull/586. This PR updates the list creation script to generate email tracker lists as well.
=> Add email category for trackers

lists2safebrowsing.py
We intend to enable RS uploads for Nightly only in fx128 [Bug 1899359 - Flip pref in url-classifier to fetch ETP lists from Remote Settings in Nightly only](https://bugzilla.mozilla.org/show_bug.cgi?id=1899359)
This PR enables RS uploads for unversioned lists, which is the latest version of the disconnect list.
=> Enable RS upload for the latest ETP list only, to serve to Nightly

lists2safebrowsing.py, publish2cloud.py, settings.py
This patch depends on #192 merging first. It is easier to review this by commit to avoid looking at code from #192 as well while reviewing
We currently have to manually request a review for updated/new records in remote settings. This patch handles automating that process.
=> Add automated review requests for updating/creating records

publish2cloud.py, rs_dev.ini, rs_prod.ini, rs_stage.ini, sample_shavar_list_creation.ini, settings.py
Aligns env variable names to what is specified [here](https://remote-settings.readthedocs.io/en/latest/support.html#how-do-i-automate-the-publication-of-records-forever). These are the items this patch covers:
- `SHAVAR_REMOTE_SETTINGS_URL` --> `SERVER`
- `SHAVAR_REMOTE_SETTINGS_USERNAME`, `SHAVAR_REMOTE_SETTINGS_PASSWORD` --> `AUTHORIZATION`
=> Align environment variable names to requirements for automation on GKE

publish2cloud.py
This error got slipped in a previous pr, where NoOptionError was not defined. This patch fixes that by accessing NoOptionError through `configparser`
=> Fixed NoOptionError is not defined error

rs_dev.ini
When creating the rs_dev.ini, I did not switch out `SHAVAR_REMOTE_SETTINGS_URL` for `SERVER`. This causes some discrepency for testing purposes and generally is not correct. This patch fixes this issue.
=> Fix breakage in rs_dev.ini file caused by use of old environment variable

publish2cloud.py, requirements.txt
This PR deals with switching from using requests to kinto-http to communicate with the remote settings server.
- Add kinto_http as a new installation in requirements.txt
- switch from using requests to using a kinto-http client for operations like `get_record` `create_record`
=> Switch to kinto-http for Remote Settings requests

publish2cloud.py, requirements.txt, settings.py
This PR deals with switching from using requests to kinto-http to communicate with the remote settings server.
What this PR changes
- Add kinto_http as a new installation in requirements.txt
- switch from using requests to using a kinto-http client for operations like get_record create_record
=> Switched to using kinto-http library

lists2safebrowsing.py
Since we don't have versioning enabled right now, it is important to run the `request_rs_review()` function before we disable rs uploads for versioned lists
=> Move review request temporarily

publish2cloud.py, settings.py
I didn't add a check if remote_settings_upload is enabled or not, and this causes breakage on the shavar side. This PR fixes that problem.
=> Add check for remote settings enabled before setting supported versions

publish2cloud.py
We recently uncovered that versionCompare treats beta as < release ` 128.0a1 < 128.0b1 < 128.0 ` which means that beta and nightly versions on 128 would receive lists for 127 due to our `filter_expression`. 
https://searchfox.org/mozilla-central/source/xpcom/base/nsVersionComparatorImpl.cpp#14
- This PR changes the `filter_expression` to compare against Nightly instead of release since ` 128.0 >128.0b1 > 128.0a1 `, which means that all versions at 128 will get the versioned lists for 128.
- Tested by checking the occurrence of `https://128-0-base-email-track-digest256.dummytracker.org` on about:url-classifier on various different firefox versions
=> Change versionCompare to use Nightly instead of Release

lists2safebrowsing.py
This PR creates a new "nightly" test domain that is added for the master branch.
When testing on url-classifier, for the latest nightly, we use
`https://nightly-base-email-track-digest256.dummytracker.org`
For all other versions, we use
`https://version_num-0-base-email-track-digest256.dummytracker.org`
where version_num is the version of the firefox client (126, 125, 130 etc.)
=> Add a nightly test tracker domain

publish2cloud.py
Currently, we only update the nightly record if the safe browsing file checksum changes. However, we also need to update the nightly records when the filter_expression is changed, but the checksum doesn't change. This could happen when we increase the version number for the nightly records.
=> Update the nightly record if the filter_expression has changed.

.gitignore, lists2safebrowsing.py, requirements-test.txt, tests/test_lists2safebrowsing.py, utils.py
This PR:
- Moves shared utilities to utils.py module to be used by webkit script in #212
- Fixes failing tests 
- Add `.venv` to ignore file
- Tracked in [FXIOS-10728](https://mozilla-hub.atlassian.net/browse/FXIOS-10728)
- Blocks #212, #213
**NOTE 1:** The only meaningful change here is that now we have a new `get_blocked_domains(config, section)` function that returns the list of domains. The other functions are moved to `utils.py` as is.
**NOTE 2:** We still have some tests failing but they are the same ones failing on main too
=> [WebkitLists] P1. Move shared utilities to `utils.py`

Dockerfile, entrypoint.sh, lists2webkit.py, publish2rs.py, requirements.txt
This PR:
- Add publish2rs script that determines what to create, update and delete based on file digest.
- Add `entrypoint.sh` as an entrypoint to docker.
- Tracked in [FXIOS-10505](https://mozilla-hub.atlassian.net/browse/FXIOS-10505)
- Depends on #212
I tested locally on the dev server adding, deleting and updating by:
- Adding `foo.json` to `webkit-lists/` and running `lists2webkit.py`
- Result: foo record with attachment is created.
- Modifying `foo.json` and running `lists2webkit.py` again
- Result: foo record is updated with new attachment.
- Deleting `foo.json` and running `lists2webkit.py` again
- Result: foo record is deleted.
- Running `lists2webkit.py` on synced version.
- Result: nothing is done and script exits successfully.
=> [WebkitLists] P3. Add `publish2rs` script to push changes to RS

constants.py, lists2safebrowsing.py, publish2cloud.py, rs_dev.ini, rs_prod.ini, rs_stage.ini, utils.py
We add the support of populating the ConsentManager category
The PR does two things
* Replace the hardcoded version checks with the `min_supported_version` config option
* Add the ConsentManager category to the lists
=> Add the ConsentManager category
