mozilla-services/shavar-list-creation

lists2safebrowsing.py

@rtilder @rfk This should fix https://github.com/mozilla-services/shavar/issues/21 after it's deployed.

Add adddel line to delete all previous chunks (fixes #8)

---

lists2safebrowsing.py

This reverts commit 52fe8d3f098fff40129ffdfa1ad9384ee7e1e1c9.
@rtilder says we need to revert this to accommodate the new non-delta-list-updates flag added in https://github.com/mozilla-services/shavar/pull/25
@sjhworkman OK to commit?

Revert "Add adddel line to deleted all previous chunks"

---

sample_shavar_list_creation.ini

This is just the sample config, but we should fix it in case someone copies/pastes from it.

Pull the disconnect list over HTTPS

---

lists2safebrowsing.py
sample_shavar_list_creation.ini

A slightly underwhelming interim fix for the existing script to publish shumway's whitelist.
r? @fmarier

Iterim shumway list addition changes

---

lists2safebrowsing.py
sample_shavar_list_creation.ini

Adds business entity whitelist: https://bugzil.la/1189087
Adds alternative tracking blacklist: https://bugzil.la/1187454

Newer tracking protection lists

---

lists2safebrowsing.py

Also: publish to S3 by default and a pair of trailing whitespace cleanups.

Lame only-publish-when-there's-new-data tweaks

---

lists2safebrowsing.py

Goes with https://github.com/mozilla-services/shavar-list-creation-config/pull/6

Remove exceptions and rename

---

lists2safebrowsing.py

I can't see how this ever worked...

Fix syntax errors in error output

---

lists2safebrowsing.py
sample_shavar_list_creation.ini

Turns out we won't be going the Shumway route but will be blocking some
additional tracking stuff.
r? @fmarier

Remove shumway; add plugin-blocklist

---

lists2safebrowsing.py
sample_shavar_list_creation.ini

Add plugin-blocklist experimentation option

---

lists2safebrowsing.py

See also mozilla-services/shavar-list-creation-config#21

bug 1369160: add infobar-exceptions

---

disconnect_mapping.py

Domains added in https://github.com/mozilla-services/shavar-prod-lists/pull/54 plus fix #63.

Update Disconnect mapping with new domains

---

lists2safebrowsing.py
sample_shavar_list_creation.ini

See https://github.com/mozilla-services/shavar-prod-lists/pull/66

bug #1559217: add new social tracking protection config section names

---

lists2safebrowsing.py
publish2cloud.py

Fix for https://github.com/mozilla-services/shavar-list-creation/issues/94 and small improvements

Make shavar list creation work without any versioning configs

---

publish2cloud.py

So maybe there are two ways to create a list in shavar and maybe we use
one not the other. Let's be sure and set object acl's either way.
I blame someone else for this not being fixed the first time.

List permissions fix No. 3 in a series

---

.circleci/config.yml
README.md

Add a configuration file that instructs CircleCI to use a docker image with Python 2.7, install the dependencies in a virtual environment, perform dependency caching, run the unit tests and store their metadata. Also, add a status badge to the README.

Configure CircleCI

---

constants.py
lists2safebrowsing.py
publish2cloud.py

Entity list on shavar-prod-lists will have a new list structure after https://github.com/mozilla-services/shavar-prod-lists/pull/235. This PR updates the entity list processing.
#
Based off of https://github.com/mozilla-services/shavar-list-creation/pull/155 but with properly signed commits

Update entity list process

---

lists2safebrowsing.py
tests/test_lists2safebrowsing.py

This PR adds unit tests for:
- `get_output_and_log_files`
- `get_list_url`
- `load_json_from_url`

Add more unit tests

---

.circleci/config.yml
README.md

This PR updates the instructions in the `README` to use the new test requirements file. Also, it updates the dependency caching key in the configuration of CircleCI, so that it includes the checksum of the test requirements file as well.

Update README and CircleCI config to use requirements-test.txt

---

constants.py
lists2safebrowsing.py
publish2cloud.py

Duplicate PR for create JSON tracking protection lists for Stage. Production changes available on #176 
#
Related to https://github.com/mozilla-services/shavar-list-creation/issues/172

Create json tracking protection lists

---

README.md

This PR adds a comment about the Shavar list creation changes on main being available to both main stage and main.

Add warning about changes being served to both stage and prod

---

Dockerfile
lists2safebrowsing.py
publish2cloud.py
rs_prod.ini
rs_stage.ini
settings.py

In order to automate uploading lists to RS, we need specific .ini files and a Dockerfiler to run `lists2safebrowsing.py` automatically.
I was unable to test these changes completely since I don't have the environment locally running. I would need some help to test this.
We will have to update readme once this gets merged in to reflect what these files do and how they are used.

Add RS automation requirements

---

publish2cloud.py
requirements.txt

Reverts mozilla-services/shavar-list-creation#193

Revert "Switch to kinto-http for Remote Settings requests"
